#!/bin/bash

# This script rebuilds the algorithmically-generated ftml files.

set -e

if [ ! -f wscript ]
then
	echo "Must be in the root of the project"
	exit 2
fi

# configure tests
tests="AllChars Proof Diac Matras Medials Guards"
urls='url(../references/PadaukBook-Regular_gr.ttf)=grR url(../references/PadaukBook-Bold_gr.ttf)=grB url(../references/tests/ftml/fonts/PadaukBook-Regular_ot_DFLT.ttf)=dfltRref url(../references/tests/ftml/fonts/PadaukBook-Bold_ot_DFLT.ttf)=dfltBref url(../references/tests/ftml/fonts/PadaukBook-Regular_ot_mym2.ttf)=Rref url(../references/tests/ftml/fonts/PadaukBook-Bold_ot_mym2.ttf)=Bref url(../results/tests/ftml/fonts/PadaukBook-Regular_ot_DFLT.ttf)=dfltR url(../results/tests/ftml/fonts/PadaukBook-Bold_ot_DFLT.ttf)=dfltB url(../results/tests/ftml/fonts/PadaukBook-Regular_ot_mym2.ttf)=R url(../results/tests/ftml/fonts/PadaukBook-Bold_ot_mym2.ttf)=B url(../references/Pyidaungsu-2.5.3_Regular.ttf)=Pyidaungsu url(../references/NotoSansMyanmar-Regular.ttf)=notoSans url(../references/NotoSerifMyanmar-Regular.ttf)=notoSerif'
ufo='source/masters/Padauk-Regular.ufo'

# list all the fonts to test
fonts=''
for url in $urls
do
	fonts="$fonts -s '$url'"
done

echo "Rebuilding ftml files..."
for test in $tests
do
	base=${test,,}
	title="\"${test} auto\""
	ftml=tests/${base}.ftml
	log=tests/logs/${base}.log
	eval tools/bin/psfgenftml.py -q -t "$title" --prevfont references/Padauk-Regular.ttf --norendercheck --scale 200 -i source/glyph_data.csv --xsl ../tools/ftml.xsl "$fonts" -l $log $ufo $ftml &
done
wait
echo "done."
