#!/bin/sh
# Script for calling multiple routines on a project, typically prior to committing to a repository.

# Stop on any errors
set -e

echo "-----Check and normalize Regular..."
# Do this before meta sync so we minimize problems in the ExtraBold
# This normalization will also run check and fix routines
psfnormalize -p checkfix=fix source/masters/Padauk-Regular.ufo

echo "-----Updating glyph orders and names in Regular..."
psfsetpsnames -q -p checkfix=none -p backup=False -i source/glyph_data.csv source/masters/Padauk-Regular.ufo
psfsetglyphorder -q -p checkfix=none -p backup=False  --header sort_final -i source/glyph_data.csv source/masters/Padauk-Regular.ufo

echo "-----Syncing glyph orders, psnames, and other metadata to other UFOs..."
psfsyncmasters source/Padauk.designspace

echo "-----Updating woff metadata file..."
psfmakewoffmetadata -n padauk -i org.sil.fonts -o source/padauk-WOFF-metadata.xml source/masters/Padauk-Regular.ufo
psfmakewoffmetadata -n padaukbook -i org.sil.fonts -o source/padaukbook-WOFF-metadata.xml source/masters/Padauk-Regular.ufo

echo "-----Check and normalize ExtraBold..."
psfnormalize -p checkfix=fix source/masters/Padauk-ExtraBold.ufo

echo "Building internal fea..."
makefea -o source/masters/Padauk-Regular.ufo/features.fea  -i source/padauk.fea -c source/padauk_classes.xml --omitaps "_R" source/masters/Padauk-Regular.ufo &
makefea -o source/masters/Padauk-ExtraBold.ufo/features.fea -i source/padauk.fea -c source/padauk_classes.xml --omitaps "_R" source/masters/Padauk-ExtraBold.ufo &
wait

echo "preflight completed!"
