#!/bin/sh

# Produce individual UFOs from Glyphs file
psfglyphs2ufo --preservefea source/masters/Padauk.glyphs source/masters

# This normalization will also run check and fix routines
psfnormalize -p checkfix=fix source/masters/Padauk-Regular.ufo
psfnormalize -p checkfix=fix source/masters/Padauk-ExtraBold.ufo

# update psnames and sort order in Regular, which also normalizes it
# psfsetpsnames -p checkfix=fix -i source/glyph_data.csv source/masters/Padauk-Regular.ufo
# psfsetglyphorder --header sort_final -i source/glyph_data.csv source/masters/Padauk-Regular.ufo

# copy psnames and glyphorder and any other updates to all fonts
psfsyncmasters source/Padauk.designspace

 # Fix problem with non-spacing marks due to glyphsLib bug
psfremovegliflibkeys source/masters/Padauk-Regular.ufo com.schriftgestaltung.Glyphs.originalWidth
psfremovegliflibkeys source/masters/Padauk-ExtraBold.ufo com.schriftgestaltung.Glyphs.originalWidth
